---
abstract: 'Object methods to create a DHCP packet.'
author:
  - 'Dean Hamstead <dean@fragfest.com.au>'
build_requires:
  File::Spec: 0
  Module::Build: 0.3601
  Test::More: 0
  Test::Warn: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-DHCP
requires:
  Carp: 0
  Exporter: 0
  List::Util: 0
  Scalar::Util: 0
  Socket: 0
  constant: 0
  perl: v5.8.0
  strict: 0
  warnings: 0
version: 0.691
