# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-DHCP
version:      0.67_1
version_from: lib/Net/DHCP/Packet.pm
abstract:     DHCP Packet encoder-decoder in pure perl
installdirs:  site
license:      perl
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
